/* VietGraph demo UI. The backend contract is intentionally small and forgiving. */
(() => {
  const $ = (selector) => document.querySelector(selector);
  const state = { result: null, cy: null, startedAt: 0 };
  const stages = ['ingest', 'extract', 'resolve', 'score', 'ready'];
  const fallback = { metadata: { title: 'Hồ Chí Minh · mẫu tiếng Việt', language: 'vi' }, graph: { nodes: [{ id: 'hcm', label: 'Hồ Chí Minh', type: 'PERSON', description: 'Nhà cách mạng và Chủ tịch đầu tiên của Việt Nam Dân chủ Cộng hòa.', evidence: 'Hồ Chí Minh là nhà cách mạng và Chủ tịch nước Việt Nam.' }, { id: 'vietnam', label: 'Việt Nam', type: 'PLACE', evidence: 'Hồ Chí Minh lãnh đạo phong trào độc lập tại Việt Nam.' }, { id: 'independence', label: 'Độc lập', type: 'CONCEPT', evidence: 'Tuyên ngôn Độc lập được đọc tại Quảng trường Ba Đình.' }, { id: 'ba-dinh', label: 'Quảng trường Ba Đình', type: 'PLACE', evidence: 'Tuyên ngôn được đọc tại Quảng trường Ba Đình.' }, { id: 'government', label: 'Chính phủ Việt Nam', type: 'ORGANISATION', evidence: 'Chính phủ lâm thời được thành lập sau Cách mạng.' }], edges: [{ source: 'hcm', target: 'vietnam', label: 'lãnh đạo' }, { source: 'hcm', target: 'independence', label: 'tuyên bố' }, { source: 'independence', target: 'ba-dinh', label: 'đọc tại' }, { source: 'hcm', target: 'government', label: 'thành lập' }] }, entities: [], triples: [], stats: { entities: 5, relations: 4, triples: 4 }, metrics: { quality_score: 0.94 } };

  function setStages(index) { stages.forEach((name, i) => { const el = document.querySelector(`[data-stage="${name}"]`); el.classList.toggle('active', i === index); el.classList.toggle('done', i < index); }); }
  function setMetric(id, value) { $(id).textContent = value ?? '—'; }
  function normalizeResult(raw) {
    const graph = raw?.graph || {}; const nodes = graph.nodes || raw?.nodes || graph.elements?.nodes || []; const edges = graph.edges || raw?.edges || graph.links || graph.elements?.edges || [];
    const cleanNodes = nodes.map((n, i) => { const d = n.data || n; return { ...d, id: String(d.id ?? d.node_id ?? `node-${i}`), label: d.label || d.name || d.text || `Node ${i + 1}`, type: String(d.type || d.entity_type || 'CONCEPT').toUpperCase(), evidence: d.evidence || d.sentence || d.context || '' }; });
    const cleanEdges = edges.map((e, i) => { const d = e.data || e; return { ...d, id: String(d.id ?? `edge-${i}`), source: String(d.source ?? d.from ?? d.subject ?? ''), target: String(d.target ?? d.to ?? d.object ?? ''), label: d.label || d.relation || d.predicate || '' }; }).filter(e => e.source && e.target);
    const stats = raw?.stats || {}; const metrics = raw?.metrics || {}; return { ...raw, graph: { nodes: cleanNodes, edges: cleanEdges }, stats: { ...stats, entities: stats.entities ?? stats.nodes ?? cleanNodes.length, relations: stats.relations ?? stats.edges ?? cleanEdges.length, triples: stats.triples ?? raw?.triples?.length ?? cleanEdges.length }, metrics };
  }
  function renderResult(raw) { const result = normalizeResult(raw); state.result = result; const nodes = result.graph.nodes; const edges = result.graph.edges; setMetric('#metricEntities', result.stats.entities); setMetric('#metricRelations', result.stats.relations); setMetric('#metricTriples', result.stats.triples); const score = result.metrics.quality_score ?? result.metrics.overall_score ?? result.metrics.quality ?? result.metrics.score; setMetric('#metricQuality', score == null ? '—' : `${Math.round(Number(score) * (Number(score) <= 1 ? 100 : 1))}%`); $('#metricQualityLabel').textContent = score == null ? 'pipeline complete' : Number(score) > .8 ? 'high confidence' : 'needs review'; setStages(4); $('#sourceStatus').textContent = 'COMPLETE'; $('#elapsed').textContent = `${((Date.now() - state.startedAt) / 1000).toFixed(1)}s`; buildGraph(nodes, edges); }
  function buildGraph(nodes, edges) { const box = $('#cy'); box.innerHTML = ''; if (!nodes.length) { box.innerHTML = '<div class="empty-graph"><strong>No entities found</strong><p>Try a longer document.</p></div>'; return; } if (typeof cytoscape === 'undefined') return; state.cy?.destroy(); state.cy = cytoscape({ container: box, elements: { nodes: nodes.map(n => ({ data: n })), edges: edges.map(e => ({ data: e })) }, layout: { name: 'cose', animate: false, padding: 30 }, style: [{ selector: 'node', style: { 'background-color': (e) => ({ PERSON: '#ff8c70', PLACE: '#55d4c4', ORGANISATION: '#9f8cff', ORG: '#9f8cff', CONCEPT: '#f2cc68' }[e.data('type')] || '#55d4c4'), label: 'data(label)', color: '#eaf2f3', 'font-size': 10, 'text-valign': 'bottom', 'text-margin-y': 8, 'border-width': 2, 'border-color': '#0c1927', width: 17, height: 17 }}, { selector: 'edge', style: { width: 1, 'line-color': '#40606a', 'target-arrow-color': '#40606a', 'target-arrow-shape': 'triangle', label: 'data(label)', color: '#7d999f', 'font-size': 8, 'curve-style': 'bezier' } }, { selector: ':selected', style: { 'border-color': '#fff', 'border-width': 3 } }] }); state.cy.on('tap', 'node', (event) => showDetail(event.target.data())); }
  function showDetail(node) { const links = state.result.graph.edges.filter(e => e.source === node.id || e.target === node.id); $('#detailPanel').innerHTML = `<div class="detail-content"><div><span class="detail-type">${escapeHtml(node.type)}</span><h3>${escapeHtml(node.label)}</h3><p>${escapeHtml(node.description || `${links.length} linked fact${links.length === 1 ? '' : 's'} in this graph.`)}</p></div><div class="evidence"><span class="evidence-label">EVIDENCE / SOURCE SENTENCE</span><blockquote>“${escapeHtml(node.evidence || 'Evidence sentence not provided by the extractor.') }”</blockquote></div></div>`; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
  async function loadSample() { const button = $('#loadSample'); button.disabled = true; button.textContent = 'Loading…'; try { const response = await fetch('/api/demo/sample'); if (!response.ok) throw new Error('Sample endpoint returned an error.'); const data = await response.json(); $('#sourceText').value = data.text || data.content || data.sample || ''; $('#charCount').textContent = $('#sourceText').value.length; } catch (error) { $('#sourceText').value = 'Hồ Chí Minh là nhà cách mạng và Chủ tịch nước Việt Nam. Tuyên ngôn Độc lập được đọc tại Quảng trường Ba Đình.'; $('#charCount').textContent = $('#sourceText').value.length; } finally { button.disabled = false; button.innerHTML = 'Load sample <span>↗</span>'; document.querySelector('[data-tab="paste"]').click(); } }
  async function runPipeline() { const text = $('#sourceText').value.trim(); if (!text) { $('#errorBox').classList.remove('hidden'); $('#errorMessage').textContent = 'Add some text or load the sample first.'; return; } $('#errorBox').classList.add('hidden'); $('#runPipeline').disabled = true; $('#sourceStatus').textContent = 'RUNNING'; state.startedAt = Date.now(); setStages(0); const timer = setInterval(() => { const active = stages.findIndex((s) => document.querySelector(`[data-stage="${s}"]`).classList.contains('active')); if (active < 3) setStages(active + 1); }, 550); try { const response = await fetch('/api/pipeline/run', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, language: 'vi', extraction: 'offline' }) }); if (!response.ok) throw new Error(`Pipeline returned ${response.status}.`); renderResult(await response.json()); } catch (error) { $('#errorBox').classList.remove('hidden'); $('#errorMessage').textContent = error.message; $('#sourceStatus').textContent = 'ERROR'; setStages(0); } finally { clearInterval(timer); $('#runPipeline').disabled = false; } }
  document.querySelectorAll('.source-tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.source-tab').forEach((t) => t.classList.toggle('active', t === tab)); document.querySelectorAll('.tab-content').forEach((c) => c.classList.add('hidden')); $(`#${tab.dataset.tab}Tab`).classList.remove('hidden'); }));
  $('#sourceText').addEventListener('input', () => { $('#charCount').textContent = $('#sourceText').value.length; }); $('#fileInput').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; $('#fileName').textContent = file.name; const reader = new FileReader(); reader.onload = () => { $('#sourceText').value = String(reader.result).slice(0, 20000); $('#charCount').textContent = $('#sourceText').value.length; document.querySelector('[data-tab="paste"]').click(); }; reader.readAsText(file); }); $('#loadSample').addEventListener('click', loadSample); $('#runPipeline').addEventListener('click', runPipeline); $('#useFallback').addEventListener('click', () => { $('#errorBox').classList.add('hidden'); state.startedAt = Date.now() - 4500; renderResult(fallback); }); $('#fitGraph').addEventListener('click', () => state.cy?.fit(undefined, 35)); $('#downloadJson').addEventListener('click', () => { if (!state.result) return; const blob = new Blob([JSON.stringify(state.result, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'vietgraph-result.json'; link.click(); URL.revokeObjectURL(url); }); $('#nodeSearch').addEventListener('input', (event) => { if (!state.cy) return; const query = event.target.value.toLowerCase(); state.cy.nodes().forEach((node) => node.style('opacity', !query || node.data('label').toLowerCase().includes(query) ? 1 : .15)); });
})();
